# test:
#   path: /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET]
#   host:
#     localhost
#     # {subdomain}.monsite.com / www.monsite.com / monsite.com
#   schemes: [https, http]

#   # defaults:
#   #     age: 0
#   # requirements:
#   #     age: \d+
